### ISSUE TITLE
reo-veo license?

### ISSUE THREAD

**Issue by dohliam** [dohliam/libreoffice-impress-templates#1]
@milekpl Thank you for the amazing templates which were the original inspiration for this project! I have managed to track down detailed licensing information for all of the templates in the [modern-impress-templates collection](https://github.com/dohliam/libreoffice-impress-templates/tree/master/modern-impress-templates) except for the ones in the `reo-veo` series.

Recently, while making [this list of licenses](https://github.com/dohliam/libreoffice-impress-templates/blob/master/modern-impress-templates/README.md), I realized that the only license provided for the `reo-veo` templates (i.e., `reo-veo1` ... `reo-veo12`) was "Free."

Unfortunately, "free" is not a license (as far as I am aware), not to mention that many people have different definitions of what "free" means (GPL? Public Domain? CC-BY?). Also, I was unable to find any information about the original author of the template and/or the art, so I wasn't really sure how to properly attribute these.

Although I believe your intention was to provide all of these templates under free licenses, it is probably better to ask you than for me to make a guess!

Would you be able to clarify the license status for the Reo Veo templates so that they can be properly credited in this project?

Thanks! :smile:

**Comment by milekpl** [comment]
Right, I don't remember exactly where I took it from. These templates no longer open in Apache OpenOffice or LibreOffice 5, but I believe the sources come from GNOME:

http://gnome-look.org/content/show.php/Reo+veo?content=90568

And you can see that the license was exactly that. They're ugly anyway, so if you want to make a fresh release, I would simply remove them.

**Comment by dohliam** [comment]
Yes, I saw the artwork earlier on gnome-look.org but wasn't sure if it had derived from your templates or the other way around. Thanks for confirming! The user is listed as "inactive" as well, so no way to ask them what they meant. It looks like you're right then, and unfortunately these will have to be removed.

By the way, I fixed the issues with the templates in the modern-impress-templates collection and they all work fine now in recent versions of LibreOffice Impress if you're still interested in using them!

**Comment by milekpl** [comment]
Yes, I noticed. Thanks! This will help other users for sure! I'm no longer using LibreOffice for creating so many presentations as I used to in the past, so I simply didn't notice they didn't work anymore. Moreover, I consider most of them pretty ugly today :(

I think it might be useful to look at freely available (and properly licensed) desktop wallpapers again, and maybe some of the less intrusive could work for modern templates. Another good source is deviantART.

**Comment by dohliam** [comment]
That's a great idea. :+1: I'm thinking now that I might replace the Reo Veo templates with 12 new ones that have a free license. I'll see if I can find some nice low-key artwork per your suggestions, and once the new templates are ready of course I'll credit you for the idea in the license information. :smile:
