### ISSUE TITLE
Templates have uneditable text

### ISSUE THREAD

**Issue by CecilFF4** [dohliam/libreoffice-impress-templates#11]
I've tried a few templates and they all suffer the same problem. There is only one editable text box on the first slide, where you're supposed to be able to edit the presentation title, course name, organization, etc. You can only edit the title, so that first slide is not useful at all.

I'm on the latest version of libreoffice (6.1.4.2). The template I'm trying to use is mars.otp from [here](https://dohliam.github.io/libreoffice-impress-templates/).

**Comment by dohliam** [comment]
Were all of the templates that you tried part of the [chtsai-impress](https://github.com/dohliam/libreoffice-impress-templates#chtsai-impress) collection by any chance? These all have a similar design.

You can edit the text boxes in the first slide by going to the `View` menu and selecting `Master` > `Slide Master` to edit the master template. (You can return to Normal view again by selecting `View` > `Normal`.)

You are right that ideally these text boxes would also be editable in the normal view. However, they are currently included in the master slide, so by default they are part of the "background objects" layer, and therefore uneditable.

**Comment by CecilFF4** [comment]
It just made sense to me that if one text box was editable, they all would be. But you were right. Sorry I made an issue of it.
