### ISSUE TITLE
Presentations Broke

### ISSUE THREAD

**Issue by Souravgoswami** [dohliam/libreoffice-impress-templates#14]
## Issue 🐞
It all worked fine when added slides and saved successfully. Problems arose when I try to reopen the saved file, I see Spanish texts, some has English texts on background that's not editable. Some of the themes got changed.

## OS 🖥
Arch Linux and using the AUR package.

## Libreoffice Version ⚙️
LibreOffice 6.2.3.2 20(Build:2)

## Screenshots 📸
![a](https://user-images.githubusercontent.com/37468605/57789398-78421400-7756-11e9-83cb-d6632e4088f6.png)
![b](https://user-images.githubusercontent.com/37468605/57789399-78daaa80-7756-11e9-82ef-87a4ee8e8be3.png)

**Comment by dohliam** [comment]
I can't reproduce this issue with the fedora-floral-green template, but it looks very similar to the Master template, so I wonder if you somehow changed the Master in some way. That would explain why the text is not editable. Try going to View > Master Slide and see if you can remove the undesired elements that way.

The Portuguese text is just default text (also for the Master slide) and says the same as the English text in your second screenshot: "Click to edit the outline text format". This also leads me to believe that you may have entered the Master view or changed the Master slide somehow.

**Comment by Souravgoswami** [comment]
That was actually weird. I reinstalled this. So far so good. When I had problem, I just saved the background image, and reused the background image - that also solved the issue. I will inform you right after I get anything like the above screenshots...
