### ISSUE TITLE
Templates for LibreOffice 5.0

### ISSUE THREAD

**Issue by Almorca** [dohliam/libreoffice-impress-templates#17]
Libreoffice has a page with designs that were requested to be added to Impress and that could be added to this page.

https://wiki.documentfoundation.org/Design/Whiteboards/Templates_for_LibreOffice_5.0

**Comment by dohliam** [comment]
Hi @Almorca, thanks for the suggestion! I believe these have already been included here -- did you have the chance to check out the [lo5-design-candidates](https://github.com/dohliam/libreoffice-impress-templates#lo5-design-candidates) collection?

**Comment by AMorenoStratio** [comment]
My fault. There are the same.

**Comment by Almorca** [comment]
My fault. There are the same.
