### ISSUE TITLE
Templates not visible - multilingual (.deb package)

### ISSUE THREAD

**Issue by de-live-gdev** [dohliam/libreoffice-impress-templates#2]
I just installed the debian package using dpkg, but the templates won't be visible, also tried restarting libreoffice.
I then found out that the package installs to `/usr/lib/libreoffice/share/template/en-US/`, but I'am not starting libreoffice in en-US language. -> Thats the cause.
**Please build the package language independent**
--> `/usr/lib/libreoffice/share/template/common/presnt/` as target directory

**Comment by dohliam** [comment]
Thanks for reporting this. This should be fixed ASAP.

**Comment by dohliam** [comment]
This should be fixed in [the latest deb package release](https://github.com/dohliam/libreoffice-impress-templates/releases/download/v2.1/libreoffice-impress-templates-all_2.1-1.deb). Let me know if you run into any further issues!
