### ISSUE TITLE
How do you install a template?

### ISSUE THREAD

**Issue by Oflameo** [dohliam/libreoffice-impress-templates#6]
I have been clicking menus for an hour trying to figure out how to load any of these templates. I have mode no progress because there is no way to browse to the directory. I can't find instructions for Libreoffice 4.

**Comment by dohliam** [comment]
You can install the templates in several ways. If you are on Ubuntu or another Debian-based distro there is an installer with step by step instructions [here](https://github.com/dohliam/libreoffice-impress-templates/wiki/Ubuntu-Debian-Install-Guide). However, they can also be installed one by one through Impress.

Here are the instructions for LibreOffice 4:

1. In Impress, click on the File Menu, then Templates, then select _Manage_. (Or press `Ctrl+Shift+N`) to enter the template manager.)
1. Click on _My Templates_ (it should be the first box on the top left).
1. Now there should be a small button labelled _Import_ at the top left corner of the window. Click on it.
1. Browse to the .otp file you would like to install and click _Open_.
1. Your presentation template should appear in the My Templates folder for future use. (If you don't see it, it may help to exit the Template Manager and open it again.)

Hope this helps. It's not as intuitive as it could be but I'll add these instructions to the main page for others who might be wondering how to install individual templates.
