### ISSUE TITLE
otp files compiled are marked as corrupted by libreoffice 6.0.2.1

### ISSUE THREAD

**Issue by archenroot** [dohliam/libreoffice-impress-templates#9]
Hi guys,

after
```
zangetsu@venus ~/devel/proj/libreoffice/libreoffice-impress-templates $ ./scripts/repack_otp.rb 
  * Template "fedora-slideshow.otp" built successfully
  * Template "user-contrib.otp" built successfully
  * Template "lo35-templates.otp" built successfully
  * Template "kde-files-org.otp" built successfully
  * Template "lo5-design-candidates.otp" built successfully
  * Template "lo51-templates.otp" built successfully
  * Template "lo-cft.otp" built successfully
  * Template "apache-oo.otp" built successfully
  * Template "modern-impress-templates.otp" built successfully
  * Template "ubuntu-odp.otp" built successfully
  * Template "lo4-design-candidates.otp" built successfully
  * Template "other.otp" built successfully
  * Template "chtsai-impress.otp" built successfully
  * Template "scripts.otp" built successfully

```

When I click on any file then it is reported as corrupted first:
![image](https://user-images.githubusercontent.com/553512/37109259-bd2dff2a-2239-11e8-8029-e56f0bc8078a.png)

When I click yes (to repair the file) it finishes with:
![image](https://user-images.githubusercontent.com/553512/37109293-d146c3fc-2239-11e8-940f-2a48978ba2e9.png)

Maybe some issue with 6 version compatibility?

**Comment by dohliam** [comment]
Wow, thanks for letting us know about this -- it definitely seems like a pretty serious incompatibility issue with the new version of LibreOffice.

The first step to resolving this would probably be to examine the internal structure of an otp file that _does_ work with version 6 and see if there are any obvious differences as compared to previous versions. Maybe there is some missing element of the XML that LibreOffice is looking for, and simply adding it in would fix it.

The other possibility is that the format for otp's has completely changed with the new version, in which case we'd have to think about providing separate templates for <6 and >6.

**Comment by dohliam** [comment]
@archenroot It would be really helpful if you could attach one of the default otp files that comes with your version of LibreOffice here so we could take a look at it.  Thanks!

**Comment by dohliam** [comment]
@archenroot Attempting to replicate this issue on version 6.0.7.3 I discovered what the issue was here -- you were executing the packaging script from the root directory. As per the instructions [here](https://github.com/dohliam/libreoffice-impress-templates/#scripts), you need to change to the subdirectory where the desired template files are located before using the script, e.g.:

    cd modern-impress-templates
    ../scripts/repack_otp.rb

As it says in the documentation:

> You MUST change directory into a collection directory for the script to work.

Closing this issue as the templates and packaging script are still working on the latest version of LibreOffice.
